{
 "title": "Huawei SAN",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "address",
    "query": "label_values(huawei_storage_component_health_status{type=\"disk\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overall system health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk health status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(huawei_storage_component_health_status{type=\"disk\"})",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Disk running status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(huawei_storage_component_running_status{type=\"disk\"})",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Ports health status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(huawei_storage_component_health_status{type=\"eth_port\"})",
     "legendFormat": "{{type}} {{id}}"
    },
    {
     "expr": "sort_desc(huawei_storage_component_health_status{type=\"sas_port\"})",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Port running status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(huawei_storage_component_running_status{type=\"eth_port\"})",
     "legendFormat": "{{type}} {{id}}"
    },
    {
     "expr": "sort_desc(huawei_storage_component_running_status{type=\"sas_port\"})",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Components health status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(huawei_storage_component_health_status{type!=\"disk\"} and huawei_storage_component_health_status{type!=\"eth_port\"} and huawei_storage_component_health_status{type!=\"sas_port\"})",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Components running status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(huawei_storage_component_running_status{type!=\"disk\"} and huawei_storage_component_running_status{type!=\"eth_port\"} and huawei_storage_component_running_status{type!=\"sas_port\"})",
     "legendFormat": "{{type}} {{id}}"
    }
   ]
  },
  {
   "title": "Remain life",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "huawei_storage_remainlife", "legendFormat": "{{type}} {{id}}" }
   ]
  },
  {
   "title": "Space allocated",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "huawei_storage_capacity_allocated/huawei_storage_capacity_total",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_controller_cpuusage{instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_controller_memoryusage{instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "RAM usage(bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_controller_memorysize{instance=\"$address\"}/100*huawei_storage_controller_memoryusage{instance=\"$address\"}",
       "legendFormat": "Used {{location}}"
      },
      {
       "expr": "huawei_storage_controller_memorysize{instance=\"$address\"}",
       "legendFormat": "Total {{location}}"
      }
     ]
    },
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "Max R/W bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_max_read_kbytes{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_max_write_kbytes{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Avg read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Avg write {{location}}"
      },
      {
       "expr": "huawei_storage_metrics_max_latency{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Max {{location}}"
      }
     ]
    },
    {
     "title": "Cache usage R/W",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_cache_usage{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_cache_usage{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "Cache usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_cache_usage{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Avg cache usage {{location}}"
      },
      {
       "expr": "huawei_storage_metrics_cache_page_usage{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Cache page usage {{location}}"
      },
      {
       "expr": "huawei_storage_metrics_cache_chunk_usage{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Cache chunk usage {{location}}"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_queue_length{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Cache hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_cache_hits{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_cache_hits{type=\"controller\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    },
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Avg read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Avg write {{name}}"
      },
      {
       "expr": "huawei_storage_metrics_max_latency{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Max {{name}}"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_queue_length{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Allocated space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_capacity_allocated{type=\"disk_pool\", instance=\"$address\"}/huawei_storage_capacity_total{type=\"disk_pool\", instance=\"$address\"}",
       "legendFormat": "Allocated {{name}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Storage pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    },
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Avg read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Avg write {{name}}"
      },
      {
       "expr": "huawei_storage_metrics_max_latency{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Max {{name}}"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_queue_length{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Allocated space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_capacity_allocated{type=\"storage_pool\", instance=\"$address\"}/huawei_storage_capacity_total{type=\"storage_pool\", instance=\"$address\"}",
       "legendFormat": "Allocated {{name}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "LUN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    },
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_queue_length{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Allocated space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_capacity_allocated{type=\"lun\", instance=\"$address\"}/huawei_storage_capacity_total{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Allocated {{name}}"
      },
      {}
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Avg read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Avg write {{name}}"
      },
      {
       "expr": "huawei_storage_metrics_max_latency{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Max {{name}}"
      }
     ]
    },
    {
     "title": "Cache hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_cache_hits{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Read {{name}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_cache_hits{type=\"lun\", instance=\"$address\"}",
       "legendFormat": "Write {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_component_temperature{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_usage{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_queue_length{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"disk\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethernet ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_port_errors{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "{{error_type}} errors {{location}}"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_usage{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_queue_length{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Avg read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Avg write {{location}}"
      },
      {
       "expr": "huawei_storage_metrics_max_latency{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Max {{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SAS ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth (MB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_mbytes{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_mbytes{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_read_iops{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "Read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_write_iops{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "Write {{location}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_port_errors{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "{{error_type}} errors {{location}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_metrics_avg_read_latency{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "Avg read {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_avg_write_latency{type=\"sas_port\", instance=\"$address\"}",
       "legendFormat": "Avg write {{location}}"
      },
      {
       "expr": "huawei_storage_metrics_max_read_latency{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Max {{location}}"
      },
      {
       "expr": "-huawei_storage_metrics_max_write_latency{type=\"eth_port\", instance=\"$address\"}",
       "legendFormat": "Max {{location}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Enclosure temperature",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "huawei_storage_component_temperature{type=\"enclosure\", instance=\"$address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}